# Generated by Django 5.0.2 on 2024-03-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_document_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
    ]
