# Generated by Django 5.0.2 on 2024-03-25 10:06

import study.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=study.models.pdf_upload_path),
        ),
    ]
