# Generated by Django 5.0.2 on 2024-03-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_pyqsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.pyqsubject')),
            ],
        ),
    ]
