# Generated by Django 4.2.11 on 2024-04-17 10:18

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_pyqquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=study.models.image_upload_path),
        ),
    ]
