# Generated by Django 5.0.2 on 2024-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_alter_assignments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
